# This is a basic workflow to help you get started with Actions

name: Build docker apache container

# Controls when the workflow will run

on: 
  release: 
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags' 
      
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the tagged Docker image
          run: docker build . --file Dockerfile --tag rikmeijer84/why:${{steps.vars.outputs.tag}}
        - name: Push the tagged Docker image
          run: docker push rikmeijer84/why:${{steps.vars.outputs.tag}}
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag rikmeijer84/why:latest
        - name: Push the latest Docker image
          run: docker push rikmeijer84/why:latest
