# This is a basic workflow to help you get started with Actions

name: Build docker apache container

# Controls when the workflow will run

on: 
  release: 
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#    inputs:
#      tag:
#        description: 'Test scenario tag' 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
#        - name: Get the version
#          id: vars
#          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
#        - name: Build the tagged Docker image
#          run: docker build . --file Dockerfile --tag rikmeijer84/why:${{github.event.inputs.tag}}
#        - name: Push the tagged Docker image
#          run: docker push rikmeijer84/why:${{github.event.inputs.tag}}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
